status_code: 200
headers: [ ]
body:
  id: "cus_JQIGp7xMy9cFw0"
  object: "customer"
  address: null
  balance: 0
  created: 1621443335
  currency: "gbp"
  default_source: null
  delinquent: false
  description: null
  discount: null
  email: null
  invoice_prefix: "16275C2"
  invoice_settings:
    custom_fields: null
    default_payment_method: null
    footer: null
  livemode: false
  metadata:
    order_id: "6735"
  name: null
  next_invoice_sequence: 1
  phone: null
  preferred_locales: []
  shipping: null
  tax_exempt: "none"
