status_code: 200
headers: []
body:
  login: dummyUser
  id: 1
  node_id: MDQ6VXNlcjE=
  avatar_url: https://github.com/images/error/octocat_happy.gif
  gravatar_id:
  url: https://api.github.com/users/dummyUser
  html_url: https://github.com/dummyUser
  followers_url: https://api.github.com/users/dummyUser/followers
  following_url: https://api.github.com/users/dummyUser/following{/other_user}
  gists_url: https://api.github.com/users/dummyUser/gists{/gist_id}
  starred_url: https://api.github.com/users/dummyUser/starred{/owner}{/repo}
  subscriptions_url: https://api.github.com/users/dummyUser/subscriptions
  organizations_url: https://api.github.com/users/dummyUser/orgs
  repos_url: https://api.github.com/users/dummyUser/repos
  events_url: https://api.github.com/users/dummyUser/events{/privacy}
  received_events_url: https://api.github.com/users/dummyUser/received_events
  type: User
  site_admin: false
  name: Peter Fisher
  company: GitHub
  blog: https://github.com/blog
  location: San Francisco
  email: octocat@github.com
  hireable: false
  bio: There once was...
  twitter_username: monatheoctocat
  public_repos: 2
  public_gists: 1
  followers: 20
  following: 0
  created_at: 2008-01-14T04=>33=>35Z
  updated_at: 2008-01-14T04=>33=>35Z
  private_gists: 81
  total_private_repos: 100
  owned_private_repos: 100
  disk_usage: 10000
  collaborators: 8
  two_factor_authentication: true
  plan: [
      name: Medium
      space: 400
      private_repos: 20
      collaborators: 0
  ]



